# Generated by Django 5.0 on 2025-02-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_order',
            new_name='data_order',
        ),
    ]
