# Generated by Django 5.0 on 2025-02-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_date_order_order_data_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_order',
            new_name='date_order',
        ),
    ]
