# Generated by Django 5.0 on 2025-02-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_data_order_order_date_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_order',
            new_name='data_order',
        ),
    ]
